"""Validate the hardware course and emit compact ACME data; no bitmap assets."""
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# Original 5x7 lettering. Each digit is one row's five bits (0..31).
LETTERING = {
    ' ': [0]*7,
    'A': [14,17,17,31,17,17,17], 'B': [30,17,17,30,17,17,30],
    'C': [14,17,16,16,16,17,14], 'D': [30,17,17,17,17,17,30],
    'E': [31,16,16,30,16,16,31], 'F': [31,16,16,30,16,16,16],
    'G': [14,17,16,23,17,17,15], 'H': [17,17,17,31,17,17,17],
    'I': [14,4,4,4,4,4,14], 'J': [7,2,2,2,18,18,12],
    'K': [17,18,20,24,20,18,17], 'L': [16,16,16,16,16,16,31],
    'M': [17,27,21,21,17,17,17], 'N': [17,25,21,19,17,17,17],
    'O': [14,17,17,17,17,17,14], 'P': [30,17,17,30,16,16,16],
    'Q': [14,17,17,17,21,18,13], 'R': [30,17,17,30,20,18,17],
    'S': [15,16,16,14,1,1,30], 'T': [31,4,4,4,4,4,4],
    'U': [17,17,17,17,17,17,14], 'V': [17,17,17,17,17,10,4],
    'W': [17,17,17,21,21,21,10], 'X': [17,17,10,4,10,17,17],
    'Y': [17,17,10,4,4,4,4], 'Z': [31,1,2,4,8,16,31],
    '0': [14,17,19,21,25,17,14], '1': [4,12,4,4,4,4,14],
    '2': [14,17,1,2,4,8,31], '3': [30,1,1,14,1,1,30],
    '4': [2,6,10,18,31,2,2], '5': [31,16,16,30,1,1,30],
    '6': [14,16,16,30,17,17,14], '7': [31,1,2,4,8,8,8],
    '8': [14,17,17,14,17,17,14], '9': [14,17,17,15,1,1,14],
    '/': [1,1,2,4,8,16,16], '[': [14,8,8,8,8,8,14],
    ']': [14,2,2,2,2,2,14], '#': [0,0,31,31,31,0,0],
}
DIRECTIONS = [(1,0),(1,1),(0,1),(-1,1),(-1,0),(-1,-1),(0,-1),(1,-1)]


def orientation(a, b, c):
    return (b[0]-a[0])*(c[1]-a[1]) - (b[1]-a[1])*(c[0]-a[0])


def intersects(a, b, c, d):
    def on(p, q, r):
        return (min(p[0],q[0]) <= r[0] <= max(p[0],q[0]) and
                min(p[1],q[1]) <= r[1] <= max(p[1],q[1]))
    values = orientation(a,b,c), orientation(a,b,d), orientation(c,d,a), orientation(c,d,b)
    if values[0]*values[1] < 0 and values[2]*values[3] < 0:
        return True
    return any(v == 0 and on(p,q,r) for v,p,q,r in (
        (values[0],a,b,c), (values[1],a,b,d), (values[2],c,d,a), (values[3],c,d,b)))


def validate(course):
    contours = [course['outline'], *course['obstacles']]
    segments = []
    for contour_index, contour in enumerate(contours):
        if len(contour) < 3:
            raise ValueError('contour needs at least 3 distinct vertices')
        area = sum(a[0]*b[1]-a[1]*b[0] for a,b in zip(contour, contour[1:]+contour[:1]))
        if not area:
            raise ValueError('contour has zero area')
        for i, a in enumerate(contour):
            b = contour[(i+1) % len(contour)]
            if any(not isinstance(n, int) or n % 2 for n in a):
                raise ValueError('vertices must use the two-pixel integer grid')
            if not (8 <= a[0] <= 310 and 8 <= a[1] <= 166):
                raise ValueError('vertex outside safe playfield')
            dx,dy = b[0]-a[0], b[1]-a[1]
            if not (dx or dy) or (dx and dy and abs(dx) != abs(dy)):
                raise ValueError('only nonzero axis-aligned or 45 degree edges supported')
            segments.append((a,b,contour_index,i,len(contour)))
    if len(segments) > 32:
        raise ValueError('course exceeds 32-segment budget')
    for i,(a,b,ci,ei,ni) in enumerate(segments):
        for c,d,cj,ej,nj in segments[i+1:]:
            if ci == cj and ((ei-ej) % ni in (1,ni-1)):
                # Adjacent edges may share an endpoint, but may not backtrack.
                if orientation(a,b,c) == orientation(a,b,d) == 0:
                    ux,uy = b[0]-a[0], b[1]-a[1]
                    vx,vy = d[0]-c[0], d[1]-c[1]
                    if ux*vx+uy*vy < 0:
                        raise ValueError('adjacent edges overlap')
                continue
            if intersects(a,b,c,d):
                raise ValueError('nonadjacent edges intersect')
    return segments


def bytes_section(name, values):
    lines = [name + ':']
    values = [v & 255 for v in values]
    for i in range(0,len(values),16):
        lines.append('!byte ' + ','.join(f'${v:02x}' for v in values[i:i+16]))
    return '\n'.join(lines)


def generate():
    course = json.loads((ROOT / 'assets/test-course.json').read_text())
    segments = validate(course)
    start, cup = course['start'], course['cup']
    lines = ['; Generated by tools/generate_assets.py. Do not edit.',
             f'BALL_X = {start[0]}', f'BALL_Y = {start[1]}',
             f'CUP_X = {cup[0]}', f'CUP_Y = {cup[1]}',
             f'COURSE_SEGMENT_COUNT = {len(segments)}']
    encoded = []
    for a,b,*_ in segments:
        dx,dy = b[0]-a[0], b[1]-a[1]
        direction = DIRECTIONS.index(((dx>0)-(dx<0), (dy>0)-(dy<0)))
        encoded += [a[0]//2, a[1]//2, direction, max(abs(dx),abs(dy))//2]
    lines.append(bytes_section('course_segments', encoded))
    rows = [0x2000+y*320 for y in range(25)]
    lines += [bytes_section('bitmap_rows_lo', rows),
              bytes_section('bitmap_rows_hi', [v>>8 for v in rows])]
    for name, trig in [('aim_steps_x',math.cos), ('aim_steps_y',math.sin)]:
        lines.append(bytes_section(name, [round(trig(i*math.tau/128)*48) for i in range(128)]))
    ball = [(x,y) for y in range(-2,3) for x in range(-2,3) if x*x+y*y <= 5]
    ring = sorted({(round(math.cos(i*math.tau/32)*5), round(math.sin(i*math.tau/32)*5))
                   for i in range(32)})
    lines += [f'BALL_POINTS = {len(ball)}', f'CUP_POINTS = {len(ring)}']
    for name, points in [('ball',ball),('cup',ring)]:
        lines += [bytes_section(name+'_dx', [p[0] for p in points]),
                  bytes_section(name+'_dy', [p[1] for p in points])]
    font = []
    for code in range(32,94):
        font += [row << 2 for row in LETTERING.get(chr(code), [0]*7)] + [0]
    lines.append(bytes_section('font', font))
    output = ROOT / 'build/assets.inc'
    output.parent.mkdir(exist_ok=True)
    output.write_text('\n\n'.join(lines)+'\n')
    print(f'Assets: {len(segments)} segments / {len(encoded)} bytes; {len(ball)+8}/32 dynamic points')


if __name__ == '__main__':
    generate()
