"""Validate the hardware course and emit compact ACME data; no bitmap assets."""
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

DIRECTIONS = [(1,0),(1,1),(0,1),(-1,1),(-1,0),(-1,-1),(0,-1),(1,-1)]


def orientation(a, b, c):
    return (b[0]-a[0])*(c[1]-a[1]) - (b[1]-a[1])*(c[0]-a[0])


def intersects(a, b, c, d):
    def on(p, q, r):
        return (min(p[0],q[0]) <= r[0] <= max(p[0],q[0]) and
                min(p[1],q[1]) <= r[1] <= max(p[1],q[1]))
    values = orientation(a,b,c), orientation(a,b,d), orientation(c,d,a), orientation(c,d,b)
    if values[0]*values[1] < 0 and values[2]*values[3] < 0:
        return True
    return any(v == 0 and on(p,q,r) for v,p,q,r in (
        (values[0],a,b,c), (values[1],a,b,d), (values[2],c,d,a), (values[3],c,d,b)))


def validate(course):
    contours = [course['outline'], *course['obstacles']]
    segments = []
    for contour_index, contour in enumerate(contours):
        if len(contour) < 3:
            raise ValueError('contour needs at least 3 distinct vertices')
        area = sum(a[0]*b[1]-a[1]*b[0] for a,b in zip(contour, contour[1:]+contour[:1]))
        if not area:
            raise ValueError('contour has zero area')
        for i, a in enumerate(contour):
            b = contour[(i+1) % len(contour)]
            if any(not isinstance(n, int) or n % 2 for n in a):
                raise ValueError('vertices must use the two-pixel integer grid')
            if not (8 <= a[0] <= 310 and 8 <= a[1] <= 166):
                raise ValueError('vertex outside safe playfield')
            dx,dy = b[0]-a[0], b[1]-a[1]
            if not (dx or dy) or (dx and dy and abs(dx) != abs(dy)):
                raise ValueError('only nonzero axis-aligned or 45 degree edges supported')
            segments.append((a,b,contour_index,i,len(contour)))
    if len(segments) > 32:
        raise ValueError('course exceeds 32-segment budget')
    for i,(a,b,ci,ei,ni) in enumerate(segments):
        for c,d,cj,ej,nj in segments[i+1:]:
            if ci == cj and ((ei-ej) % ni in (1,ni-1)):
                # Adjacent edges may share an endpoint, but may not backtrack.
                if orientation(a,b,c) == orientation(a,b,d) == 0:
                    ux,uy = b[0]-a[0], b[1]-a[1]
                    vx,vy = d[0]-c[0], d[1]-c[1]
                    if ux*vx+uy*vy < 0:
                        raise ValueError('adjacent edges overlap')
                continue
            if intersects(a,b,c,d):
                raise ValueError('nonadjacent edges intersect')
    return segments


def bytes_section(name, values):
    lines = [name + ':']
    values = [v & 255 for v in values]
    for i in range(0,len(values),16):
        lines.append('!byte ' + ','.join(f'${v:02x}' for v in values[i:i+16]))
    return '\n'.join(lines)


def generate():
    course = json.loads((ROOT / 'assets/test-course.json').read_text())
    segments = validate(course)
    start, cup = course['start'], course['cup']
    lines = ['; Generated by tools/generate_assets.py. Do not edit.',
             f'START_X = {start[0]}', f'START_Y = {start[1]}',
             f'CUP_X = {cup[0]}', f'CUP_Y = {cup[1]}',
             f'COURSE_SEGMENT_COUNT = {len(segments)}']
    encoded = []
    for a,b,ci,*_ in segments:
        dx,dy = b[0]-a[0], b[1]-a[1]
        direction = DIRECTIONS.index(((dx>0)-(dx<0), (dy>0)-(dy<0)))
        contour = [course['outline'], *course['obstacles']][ci]
        area = sum(p[0]*q[1]-p[1]*q[0] for p,q in zip(contour,contour[1:]+contour[:1]))
        normal = (direction + (2 if (area > 0) == (ci == 0) else -2)) % 8
        encoded += [a[0]//2, a[1]//2, b[0]//2, b[1]//2, normal]
    lines.append(bytes_section('course_segments', encoded))
    rows = [0x2000+y*320 for y in range(25)]
    lines += [bytes_section('bitmap_rows_lo', rows),
              bytes_section('bitmap_rows_hi', [v>>8 for v in rows])]
    quarter = [round(math.cos(i*math.tau/128)*256) for i in range(33)]
    lines += [bytes_section('unit_cos_lo',quarter), bytes_section('unit_cos_hi',[v>>8 for v in quarter])]
    ball = [(x,y) for y in range(-2,3) for x in range(-2,3) if x*x+y*y <= 5]
    ring = sorted({(round(math.cos(i*math.tau/32)*5), round(math.sin(i*math.tau/32)*5))
                   for i in range(32)})
    lines += [f'BALL_POINTS = {len(ball)}', f'CUP_POINTS = {len(ring)}']
    for name, points in [('ball',ball),('cup',ring)]:
        lines += [bytes_section(name+'_dx', [p[0] for p in points]),
                  bytes_section(name+'_dy', [p[1] for p in points])]
    output = ROOT / 'build/assets.inc'
    output.parent.mkdir(exist_ok=True)
    output.write_text('\n\n'.join(lines)+'\n')
    print(f'Assets: {len(segments)} segments / {len(encoded)} bytes; {len(ball)+8}/32 dynamic points')


if __name__ == '__main__':
    generate()
